# Generated by Django 3.2 on 2023-12-27 20:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='api.car', verbose_name='ID автомобиля'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.PositiveIntegerField(error_messages={'validators': 'Оценка от 1 до 5!'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='оценка'),
        ),
    ]
