# Generated by Django 3.2 on 2023-12-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231227_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='api.car', verbose_name='ID автомобиля')),
                ('rates_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='api.rate', verbose_name='Рейтинг')),
            ],
        ),
    ]
