# Generated by Django 3.2 on 2023-12-27 22:32

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=256, validators=[api.validators.validate_car], verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='оценка'),
        ),
    ]
